Almost finished climber subsystem
BitBucketsFRC4183/FRC2019_Destination_Deep_Space pull request #53
Opened 2019-02-03 18:46 UTC by SRothGordon

2019-02-04 04:53 UTC, cpostbitbuckets commented on DestinationDeepSpace/src/main/java/frc/robot/subsystem/climber/ClimberSubsystem.java
> +	WPI_TalonSRX  climbMotor1;
Try to avoid simple whitespace changes. Ideally we should have a formatter to keep everything consistent, but we don't.

2019-02-04 05:08 UTC, cpostbitbuckets requested changes

2019-02-04 05:08 UTC, cpostbitbuckets commented on DestinationDeepSpace/src/main/java/frc/robot/subsystem/climber/ClimberSubsystem.java
> +		System.out.println(state);
Don't put printlns in periodic. We should use the dashboard for this sort of diagnostic.

2019-02-04 05:08 UTC, cpostbitbuckets commented on DestinationDeepSpace/src/main/java/frc/robot/subsystem/climber/ClimberSubsystem.java
> +		if (climbMotor1.getSensorCollection().isFwdLimitSwitchClosed()) {
Do we only disable the motors if the forward limit switch is hit? not the reverse limit switch?

2019-02-05 02:37 UTC, RocketRedNeck commented on DestinationDeepSpace/src/main/java/frc/robot/subsystem/climber/ClimberSubsystem.java
> +	WPI_TalonSRX  climbMotor1;
Agreed. It just slows down the review.

2019-02-05 02:38 UTC, RocketRedNeck commented on DestinationDeepSpace/src/main/java/frc/robot/subsystem/climber/ClimberSubsystem.java
> +		if (climbMotor1.getSensorCollection().isFwdLimitSwitchClosed()) {
It depends on how many switches we have; we can add a switch to both front and back so if we use power to bring the climber back down we don't damage it. We should spec it like that in hardware.

2019-02-05 06:58 UTC, RocketRedNeck commented on DestinationDeepSpace/src/main/java/frc/robot/subsystem/climber/ClimberSubsystem.java
> +		System.out.println(state);
Correct. It is better to make state display as a dashboard entry; In this case, your states are just an enumeration, but for other subsystems using commands as the state, the base class already displays the current command. So adding an enumeration display for your state variable is fine.

2019-02-06 03:13 UTC, RocketRedNeck commented
Accepting now and will fix on the other side.

2019-02-06 03:14 UTC, merged