Autonomous Code 1.0
BitBucketsFRC4183/FRC2019_Destination_Deep_Space pull request #72
Opened 2019-10-13 19:16 UTC by calculusrobotics

yay auto

2019-10-15 02:03 UTC, cpostbitbuckets requested changes
Not gonna lie, I didn't work through all the math and logic while doing this review. 

My only worry is I don't know if the driver can turn off auto if they don't want it and re-enabled teleop during auto like we have before. 

Also, before merging, we should test it on a live robot (I know that's what you really wanted to do anyway).

2019-10-15 02:03 UTC, cpostbitbuckets commented on DestinationDeepSpace/src/main/java/frc/robot/Robot.java
> -    teleopInit();
This will just disable teleop during autonomous mode, won't it? Don't we need that if doAuto is false?

2019-10-15 02:03 UTC, cpostbitbuckets commented on DestinationDeepSpace/src/main/java/frc/robot/Robot.java
> -    teleopPeriodic();
We should check for doAuto here.

2019-10-15 02:03 UTC, cpostbitbuckets commented on DestinationDeepSpace/src/main/java/frc/robot/subsystem/autonomous/AutoPeriod.java
> +            PathFinder.PathType.QUINTIC_HERMITE, // 254 uses quintic so here we are
Ha!

2019-10-15 02:03 UTC, cpostbitbuckets commented on DestinationDeepSpace/src/main/java/frc/robot/subsystem/autonomous/AutonomousConstants.java
> +	public static final Waypoint END_LEFT  = new Waypoint(FieldConstants.END_X, -FieldConstants.END_Y, 0);
This should be called something like CARGOSHIP_FRONT_LEFT and CARGOSHIP_FRONT_RIGHT. I know it's the end of the path, but it really means where you are ending up on the field.

2019-10-15 02:03 UTC, cpostbitbuckets commented on DestinationDeepSpace/src/main/java/frc/robot/subsystem/autonomous/motion/MotionPoint.java
> +    public double left_vel;
With all these underscores, lowercase letters, and terse variable names we should just be programming python. ;)

2019-10-15 02:03 UTC, cpostbitbuckets commented on DestinationDeepSpace/src/main/java/frc/robot/subsystem/drive/DriveConstants.java
> +    // TODO: i feel like this is already a thing somewhere...
I did a search and found this code (with fitting comment) in DriveSubsystem.java

```java
	/// TODO: Move to DriveConstants and rename
	public double inchesToNativeTicks(double inches) {
		return (double)DriveConstants.DRIVE_MOTOR_NATIVE_TICKS_PER_REV * (inches / DriveConstants.WHEEL_CIRCUMFERENCE_INCHES);
	}
```

2019-10-16 04:49 UTC, howard-beck commented on DestinationDeepSpace/src/main/java/frc/robot/Robot.java
> -    teleopInit();
teleopInit() starts drive and scoring init() but we want the auto versions, so in the next few lines I tested for doAuto to start drive and scoring auto, else drive and scoring init, and then regardless of auto or not the code would start climb auto so we wouldn't need to worry about teleopInit or not

2019-10-16 04:51 UTC, calculusrobotics commented on DestinationDeepSpace/src/main/java/frc/robot/Robot.java
> -    teleopPeriodic();
I just went ahead and removed teleopPeriodic because it doesn't call any methods anyways. Everything gets done by  C O M M A N D S

2019-10-16 04:53 UTC, calculusrobotics commented on DestinationDeepSpace/src/main/java/frc/robot/subsystem/autonomous/AutoPeriod.java
> +            PathFinder.PathType.QUINTIC_HERMITE, // 254 uses quintic so here we are
well actually its because a quintic spline ensures a continuous second derivative which implies a continuous curvature and therefore a continuous turn rate so we don't rapidly change motor velocities - so basically bc 254 uses them

2019-10-16 04:54 UTC, calculusrobotics commented on DestinationDeepSpace/src/main/java/frc/robot/subsystem/autonomous/motion/MotionPoint.java
> +    public double left_vel;
Saba first wrote the code in MATLAB which is just really fancy Python basically and then translated to Java so yeah pretty much

2019-10-16 04:54 UTC, calculusrobotics commented on DestinationDeepSpace/src/main/java/frc/robot/subsystem/drive/DriveConstants.java
> +    // TODO: i feel like this is already a thing somewhere...
oh thanks lol

2019-10-16 05:00 UTC, calculusrobotics commented on DestinationDeepSpace/src/main/java/frc/robot/subsystem/autonomous/AutonomousConstants.java
> +	public static final Waypoint END_LEFT  = new Waypoint(FieldConstants.END_X, -FieldConstants.END_Y, 0);
good point, I also wasn't really trying to make it the best looking code but rather just code that (would hypothetically have) worked before state. I guess my thinking was that start/mid/end is more general and could be applied to following years hab/cargoship is more specific to this year. But we don't really know is we can apply any kind of spline defined by 3 points anyways in years to come so yeah I should've gone with that. we can use more specific naming for year's equivalent of full rocket auto :)

2020-07-25 22:30 UTC, closed without merging